// Generated by CoffeeScript 2.0.1
var Tribble;

Tribble = (function() {
  class Tribble {
    constructor() {
      this.isAlive = true;
      Tribble.count++;
    }

    // prototype properties
    breed() {
      if (this.isAlive) {
        return new Tribble;
      }
    }

    die() {
      if (this.isAlive) {
        Tribble.count--;
      }
      return this.isAlive = false;
    }

    static makeTrouble() {
      var i;
      return console.log(((function() {
        var j, ref, results;
        results = [];
        for (i = j = 1, ref = this.count; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
          results.push('Trouble!');
        }
        return results;
      }).call(this)).join(' '));
    }

  };

  // class-level properties
  Tribble.count = 0;

  return Tribble;

})();
