// Generated by CoffeeScript 2.0.1
(function() {
  var cube, odd;

  cube = function(num) {
    return Math.pow(num, 3);
  };

  console.log(cube(9));

  odd = function(num) {
    return num % 2 === 1;
  };

  console.log(odd(6));

}).call(this);
