// Generated by CoffeeScript 2.0.1
var Gift, gift1, gift2;

Gift = function(name) {
  this.name = name;
  Gift.count++;
  this.day = Gift.count;
  return this.announce();
};

Gift.count = 0;

Gift.prototype.announce = function() {
  return console.log(`On day ${this.day} of Christmas I received ${this.name}`);
};

gift1 = new Gift("a partridge in a pear tree");

gift2 = new Gift("two turtle doves");
