// Generated by CoffeeScript 2.0.1
var Cow, cow1, cow2;

Cow = (function() {
  class Cow {
    constructor(cowname) {
      this.name = cowname;
      Cow.count++;
    }

    moo() {
      return console.log(`Moo! Moo! I am ${this.name}. Moo!`);
    }

  };

  Cow.count = 0;

  return Cow;

})();

cow1 = new Cow("Lizzie");

cow1.moo();

cow2 = new Cow("Billy");

console.log(`There are ${Cow.count} cows around`);
