// Generated by CoffeeScript 2.0.1
var Dog, Pet;

Pet = class Pet {
  constructor() {
    this.isHungry = true;
  }

  eat() {
    return this.isHungry = false;
  }

};

Dog = class Dog extends Pet {
  eat() {
    console.log("*crunch, crunch");
    return super.eat();
  }

  fetch() {
    console.log("Yip yip!");
    return this.isHungry = true;
  }

};
