// Generated by CoffeeScript 2.0.1
var Boy, sue;

Boy = function() {};

Boy.prototype.sing = function() {
  return console.log("It ain't easy being a boy named Sue");
};

sue = new Boy();

sue.sing();
