// Generated by CoffeeScript 2.0.1
var odd;

odd = function(num) {
  if (typeof num !== 'number') {
    throw `${num} is not a number`;
  }
  if (num !== Math.round(num)) {
    throw `${num} is not an integer`;
  }
  if (!(num > 0)) {
    throw `${num} is not positive`;
  }
  return num % 2 === 1;
};
